/**
 * EvolutionTable.h - Reverse evolution lineage (what a species+form evolved FROM).
 *
 * Auto-generated by tools/gen_evolutions.py from PKHeX's evos_*.pkl.
 * DO NOT EDIT BY HAND -- rerun the generator instead.
 *
 * Per game, because the chains differ: Pichu is absent from Let's Go, so a Pikachu
 * there has no ancestor, and a Hisuian form's ancestor is not its Kantonian one.
 * An edge is present only when both ends exist in that game.
 *
 * Layer 3 legality is the caller: an encounter template names the species that was
 * caught, so an evolved Pokemon has to be matched against its pre-evolution's slots.
 */
#ifndef PKM_EVOLUTION_TABLE_H
#define PKM_EVOLUTION_TABLE_H

#include <cstdint>

#include "Enums/GameVersion.h"

namespace Pokemon {

    /// Longest pre-evolution chain the tables can hold (real max is 2 -- Bulbasaur ->
    /// Ivysaur -> Venusaur gives Venusaur two ancestors; the extra slot is slack).
    constexpr int EVO_MAX_CHAIN = 4;

    /**
     * Immediate pre-evolution of (species, form) in `group`.
     *
     * Returns false when the species is the base of its chain, when the group has no
     * table, or when either end is absent from that game -- all of which mean "nothing
     * evolved into this here", never "unknown".
     */
    bool getPreEvolution(Enums::GameVersion group, uint16_t species, uint8_t form,
                         uint16_t& outSpecies, uint8_t& outForm);

    /**
     * Full pre-evolution chain for (species, form), nearest ancestor first.
     *
     * Writes at most `max` entries and returns how many were written. The species
     * itself is NOT included.
     */
    int getPreEvolutionChain(Enums::GameVersion group, uint16_t species, uint8_t form,
                             uint16_t* outSpecies, uint8_t* outForm, int max);
}

#endif  // PKM_EVOLUTION_TABLE_H
