/**
 * EncounterTable.h - Per-game encounter templates for Layer 3 legality.
 *
 * Auto-generated by tools/gen_encounters.py from PKHeX's wild-slot binaries and
 * static/gift/trade/raid tables. DO NOT EDIT BY HAND -- rerun the generator instead.
 *
 * One flat row per template. Wild and raid rows are MERGED per
 * (species, form, location, constraints): the level span is the union of the
 * contributing slots and the guaranteed-31 count their minimum, which is permissive
 * by construction -- merging can widen what the table accepts, never narrow it.
 * Static / gift / trade rows are never merged; each is a distinct template whose
 * fixed data has to stay exact.
 *
 * The ability slot is deliberately absent: Ability Capsule and Ability Patch let a
 * legitimate Pokemon hold a slot its encounter never offered, so the column would
 * only enable a check that false-flags real saves. Layer 2 already verifies the
 * ability against the species.
 */
#ifndef LEGALITY_ENCOUNTER_TABLE_H
#define LEGALITY_ENCOUNTER_TABLE_H

#include <cstdint>

#include "Enums/GameVersion.h"

namespace Legality {

    /// How the Pokemon was obtained. Reported verbatim, so keep the wording usable.
    enum EncounterKind : uint8_t {
        ENC_KIND_WILD   = 0,
        ENC_KIND_STATIC = 1,
        ENC_KIND_GIFT   = 2,
        ENC_KIND_TRADE  = 3,
        ENC_KIND_RAID   = 4,
    };

    /// Shiny policy of a template -- Never is a shiny LOCK, Always a forced shiny.
    enum EncounterShiny : uint8_t {
        ENC_SHINY_RANDOM = 0,
        ENC_SHINY_NEVER  = 1,
        ENC_SHINY_ALWAYS = 2,
    };

    enum EncounterFlag : uint8_t {
        ENC_FLAG_FATEFUL = 1 << 0,  ///< sets the fateful-encounter (event) bit
        ENC_FLAG_ALPHA   = 1 << 1,  ///< Legends Alpha (PLA / Z-A)
        ENC_FLAG_BOOST60 = 1 << 2,  ///< SW/SH Wild Area: post-game boosts levels to 60
        ENC_FLAG_EGG     = 1 << 3,  ///< handed over as an egg
    };

    constexpr uint8_t ENC_FORM_ANY   = 0xFF;  ///< slot randomises the form
    constexpr uint8_t ENC_GENDER_ANY = 0xFF;
    constexpr uint8_t ENC_NATURE_ANY = 0xFF;

    /// Locations that stand for a whole region rather than one place. SW/SH
    /// distribution raids are the only user: the den is anonymous, so any Wild Area
    /// location of the right DLC tier is a legal met location.
    constexpr uint16_t ENC_LOC_SWSH_WILDAREA     = 0xFFF0;  ///< Galar Wild Area
    constexpr uint16_t ENC_LOC_SWSH_WILDAREA_IOA = 0xFFF1;  ///< + Isle of Armor
    constexpr uint16_t ENC_LOC_SWSH_WILDAREA_ALL = 0xFFF2;  ///< + Crown Tundra

    struct EncounterRow {
        uint16_t species;
        uint16_t location;     ///< met location, in the ORIGIN game's namespace
        uint16_t eggLocation;  ///< 0 unless the template hands over an egg
        uint8_t  form;         ///< ENC_FORM_ANY when the slot randomises it
        uint8_t  levelMin;
        uint8_t  levelMax;
        uint8_t  versions;     ///< bit 0 / bit 1 = the group's first / second game
        uint8_t  kind;         ///< EncounterKind
        uint8_t  shiny;        ///< EncounterShiny
        uint8_t  gender;       ///< 0 male, 1 female, 2 genderless, ENC_GENDER_ANY
        uint8_t  fixedBall;    ///< 0 = the encounter does not fix the ball
        uint8_t  flawlessIVs;  ///< guaranteed count of 31 IVs
        uint8_t  nature;       ///< ENC_NATURE_ANY unless the template forces one
        uint8_t  flags;        ///< EncounterFlag bits
    };

    /// Where a game's eggs come from and where they may hatch.
    struct EggRule {
        uint16_t eggLocation;     ///< nursery id stamped into the egg-location field.
                                  ///< 0 means the FORMAT has no such field (Gen 3 alone),
                                  ///< which is why an egg there has to be inferred instead.
        uint16_t eggLocationAlt;  ///< id a TRADED egg carries instead (0 = none)
        /// Per-location version mask: bit 0 / bit 1 set when an egg may hatch at that met
        /// location in the group's first / second game. An egg hatches wherever the player
        /// is walking, so this is a permitted SET, not one place -- Gen 3 is the exception
        /// and gets a one-entry mask, because its met location is stamped on receipt.
        /// nullptr when the game has no breeding.
        const uint8_t* hatchLocations;
        uint16_t hatchLocationCount;
        uint8_t  hatchLevel;      ///< met level of a hatched egg
        uint8_t  hasBreeding;     ///< 0 for the games with no daycare at all
    };

    struct EncounterTable {
        const EncounterRow* rows;
        uint32_t rowCount;
        /// speciesIndex[s] .. speciesIndex[s + 1] bounds the rows for species s.
        const uint16_t* speciesIndex;
        uint16_t speciesIndexLen;
        /// Species bitset: could a Pokemon here have hatched from a daycare egg?
        /// nullptr when the game has no breeding.
        const uint8_t* breedable;
        EggRule egg;
    };

    /// Encounter data for a game or game group; nullptr when PKSE has none for it
    /// (every generation before Gen 3, Pokemon GO, and anything unrecognised).
    const EncounterTable* getEncounterTable(Enums::GameVersion versionOrGroup);

    /// Row version bit for an exact version id (0 when it names a group, not a game).
    uint8_t encounterVersionBit(Enums::GameVersion version);

    /// True when a met location satisfies a row's location, resolving the region
    /// sentinels above.
    bool encounterLocationMatches(uint16_t rowLocation, uint16_t metLocation);
}

#endif  // LEGALITY_ENCOUNTER_TABLE_H
