#!/usr/bin/env python3
"""Generate include/Pokemon/EvolutionTable.h + src/Pokemon/EvolutionTable.cpp -- the
per-game REVERSE evolution lineage (what a species+form evolved FROM).

Layer 3 legality needs this at runtime. An encounter template records the species that
was actually caught, so a Charizard met on Route 3 has to be matched against the
*Charmander* slot there; without the lineage every evolved Pokemon reads as "no
encounter produces this species". gen_learnsets.py already walks the same lineage, but
it folds the result into its move bitsets at generation time and never emits the edges,
so there is nothing to reuse at runtime.

Source: PKHeX's evos_<game>.pkl, read exactly as gen_learnsets.read_evolutions does
(EvolutionReversePersonal.GetLineage -- walk every source species+form, register the
reverse edge for each destination it leads to, first source wins). This script imports
those helpers rather than restating them, so the two tables can never disagree about
what an ancestor is.

The lineage is PER GAME because the games disagree: Pichu is absent from Let's Go, so a
Pikachu there did not evolve from one, and a regional form's chain differs from its
Kantonian counterpart's. Edges whose source is not present in that game are dropped for
the same reason gen_learnsets skips them.

Regenerate:  python tools/gen_evolutions.py
Pulls the PKHeX resources it reads from GitHub on demand (tools/pkhex_source.py);
no local PKHeX checkout required.
"""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
# gen_learnsets owns the PKHeX personal/evolution binary readers; importing keeps the
# two generators reading the lineage through one implementation.
from gen_learnsets import (  # noqa: E402
    EVO_RESOURCE, GAMES_TO_EMIT, GAME_VERSION_IDS, MAX_EVO_DEPTH,
    Personal, Personal3, read_evolutions,
)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_H = os.path.join(ROOT, "include", "Pokemon", "EvolutionTable.h")
OUT_CPP = os.path.join(ROOT, "src", "Pokemon", "EvolutionTable.cpp")


def build(game, pers):
    """Reverse lineage for one game -> sorted [(dstSp, dstForm, srcSp, srcForm)].

    An edge is kept only when BOTH ends are present in the game: an ancestor the game
    does not have is not an ancestor you could have evolved from there.
    """
    rev = read_evolutions(EVO_RESOURCE[game], pers)
    out = []
    for (dsp, dform), (ssp, sform) in rev.items():
        if not pers.present(dsp, dform) or not pers.present(ssp, sform):
            continue
        out.append((dsp, dform, ssp, sform))
    out.sort()
    return out


def emit_header():
    return '''/**
 * EvolutionTable.h - Reverse evolution lineage (what a species+form evolved FROM).
 *
 * Auto-generated by tools/gen_evolutions.py from PKHeX's evos_*.pkl.
 * DO NOT EDIT BY HAND -- rerun the generator instead.
 *
 * Per game, because the chains differ: Pichu is absent from Let's Go, so a Pikachu
 * there has no ancestor, and a Hisuian form's ancestor is not its Kantonian one.
 * An edge is present only when both ends exist in that game.
 *
 * Layer 3 legality is the caller: an encounter template names the species that was
 * caught, so an evolved Pokemon has to be matched against its pre-evolution's slots.
 */
#ifndef PKM_EVOLUTION_TABLE_H
#define PKM_EVOLUTION_TABLE_H

#include <cstdint>

#include "Enums/GameVersion.h"

namespace Pokemon {

    /// Longest pre-evolution chain the tables can hold (real max is 2 -- Bulbasaur ->
    /// Ivysaur -> Venusaur gives Venusaur two ancestors; the extra slot is slack).
    constexpr int EVO_MAX_CHAIN = %d;

    /**
     * Immediate pre-evolution of (species, form) in `group`.
     *
     * Returns false when the species is the base of its chain, when the group has no
     * table, or when either end is absent from that game -- all of which mean "nothing
     * evolved into this here", never "unknown".
     */
    bool getPreEvolution(Enums::GameVersion group, uint16_t species, uint8_t form,
                         uint16_t& outSpecies, uint8_t& outForm);

    /**
     * Full pre-evolution chain for (species, form), nearest ancestor first.
     *
     * Writes at most `max` entries and returns how many were written. The species
     * itself is NOT included.
     */
    int getPreEvolutionChain(Enums::GameVersion group, uint16_t species, uint8_t form,
                             uint16_t* outSpecies, uint8_t* outForm, int max);
}

#endif  // PKM_EVOLUTION_TABLE_H
''' % MAX_EVO_DEPTH


def emit_cpp(tables):
    L = []
    L.append('/**')
    L.append(' * EvolutionTable.cpp - Per-game reverse evolution lineage.')
    L.append(' *')
    L.append(' * Auto-generated by tools/gen_evolutions.py. DO NOT EDIT BY HAND.')
    L.append(' */')
    L.append('#include "Pokemon/EvolutionTable.h"')
    L.append('')
    L.append('namespace Pokemon {')
    L.append('')
    L.append('    namespace {')
    L.append('        // One reverse edge: (species, form) evolved from (fromSpecies, fromForm).')
    L.append('        // Rows are sorted by (species, form) so a lookup can binary-search.')
    L.append('        struct EvoEdge {')
    L.append('            uint16_t species;')
    L.append('            uint8_t  form;')
    L.append('            uint16_t fromSpecies;')
    L.append('            uint8_t  fromForm;')
    L.append('        };')
    L.append('')

    for game in GAMES_TO_EMIT:
        rows = tables[game]
        L.append('        const EvoEdge EVO_%s[%d] = {' % (game, len(rows)))
        for i in range(0, len(rows), 4):
            chunk = rows[i:i + 4]
            L.append('            ' + ' '.join(
                '{%4d,%2d,%4d,%2d},' % r for r in chunk))
        L.append('        };')
        L.append('')

    L.append('        struct EvoTable {')
    L.append('            const EvoEdge* rows;')
    L.append('            uint32_t count;')
    L.append('        };')
    L.append('')
    L.append('        // Resolve a game (or game group) to its lineage. Individual version ids map')
    L.append('        // to their group\'s table -- Sword and Shield share one evolution graph.')
    L.append('        bool lookupTable(Enums::GameVersion group, EvoTable& out) {')
    L.append('            switch (group) {')
    for game in GAMES_TO_EMIT:
        for vid in GAME_VERSION_IDS[game]:
            L.append('                case Enums::GameVersion::%s:' % vid)
        L.append('                    out = EvoTable{ EVO_%s, %d }; return true;' % (game, len(tables[game])))
    L.append('                default:')
    L.append('                    return false;')
    L.append('            }')
    L.append('        }')
    L.append('    }')
    L.append('')
    L.append('    bool getPreEvolution(Enums::GameVersion group, uint16_t species, uint8_t form,')
    L.append('                         uint16_t& outSpecies, uint8_t& outForm) {')
    L.append('        EvoTable t{};')
    L.append('        if (!lookupTable(group, t)) return false;')
    L.append('        uint32_t lo = 0, hi = t.count;')
    L.append('        while (lo < hi) {')
    L.append('            const uint32_t mid = lo + ((hi - lo) >> 1);')
    L.append('            const EvoEdge& e = t.rows[mid];')
    L.append('            if (e.species < species || (e.species == species && e.form < form)) lo = mid + 1;')
    L.append('            else hi = mid;')
    L.append('        }')
    L.append('        if (lo >= t.count) return false;')
    L.append('        const EvoEdge& e = t.rows[lo];')
    L.append('        if (e.species != species || e.form != form) return false;')
    L.append('        outSpecies = e.fromSpecies;')
    L.append('        outForm = e.fromForm;')
    L.append('        return true;')
    L.append('    }')
    L.append('')
    L.append('    int getPreEvolutionChain(Enums::GameVersion group, uint16_t species, uint8_t form,')
    L.append('                             uint16_t* outSpecies, uint8_t* outForm, int max) {')
    L.append('        int n = 0;')
    L.append('        uint16_t curSp = species;')
    L.append('        uint8_t curForm = form;')
    L.append('        while (n < max) {')
    L.append('            uint16_t pSp; uint8_t pForm;')
    L.append('            if (!getPreEvolution(group, curSp, curForm, pSp, pForm)) break;')
    L.append('            // Guard a cyclic data error: a chain that revisits a node would spin here.')
    L.append('            bool seen = (pSp == species && pForm == form);')
    L.append('            for (int i = 0; i < n && !seen; ++i)')
    L.append('                seen = (outSpecies[i] == pSp && outForm[i] == pForm);')
    L.append('            if (seen) break;')
    L.append('            outSpecies[n] = pSp;')
    L.append('            outForm[n] = pForm;')
    L.append('            ++n;')
    L.append('            curSp = pSp;')
    L.append('            curForm = pForm;')
    L.append('        }')
    L.append('        return n;')
    L.append('    }')
    L.append('}')
    L.append('')
    return "\n".join(L)


def main():
    personals = {g: Personal(g) for g in GAMES_TO_EMIT if g != "FRLG"}
    personals["FRLG"] = Personal3()

    tables = {}
    for game in GAMES_TO_EMIT:
        tables[game] = build(game, personals[game])
        print("  %-5s reverse edges: %4d" % (game, len(tables[game])))

    with open(OUT_H, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(emit_header())
    print("Wrote", OUT_H)
    with open(OUT_CPP, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(emit_cpp(tables))
    print("Wrote", OUT_CPP)

    total = sum(len(t) for t in tables.values())
    print("  TABLE TOTAL: %d edges, %d B" % (total, total * 6))


if __name__ == "__main__":
    main()
